In [11]:
import pandas as pd
import numpy as np
import cmake
import dlib
import face_recognition as fr
import os
import cv2
import csv
from datetime import datetime

In [12]:
path='class_list'
class_path=os.listdir(path)
print(class_path)

['madhuri.jpeg', 'Anushka.jpeg', 'sandra.jpeg', 'sidhi.jpeg', 'jordon.jpeg']


In [13]:
std_images=[]
std_name=[]
for img in class_path:
    img_path=os.path.join(path,img)
    # print(img_path)
    img_read=cv2.imread(img_path)
    # print(img_read)
    std_images.append(img_read)
    std_name.append(img[:-5])
print(std_name)

['madhuri', 'Anushka', 'sandra', 'sidhi', 'jordon']


In [14]:
# Face_Location & Encoding
def face_encoding(std_images):
    encoded_list=[]
    for img_pixels in std_images:
        img=cv2.cvtColor(img_pixels,cv2.COLOR_BGR2RGB)
        face_loc=fr.face_locations(img)
        face_enc=fr.face_encodings(img,face_loc)[0]
        encoded_list.append(face_enc)
    return encoded_list   
          

In [15]:
encoded_student_faces=face_encoding(std_images)
print(encoded_student_faces)

[array([-1.47208139e-01,  6.83678221e-03,  1.21093109e-01, -6.48979768e-02,
       -1.37596384e-01, -1.40707232e-02, -1.05128698e-01, -6.30208179e-02,
        1.50300369e-01, -1.95485905e-01,  1.72178954e-01, -4.14204448e-02,
       -2.41033807e-01,  4.51386720e-02, -5.56115732e-02,  2.32179224e-01,
       -2.07687035e-01, -2.16385543e-01, -8.54331106e-02, -1.03155017e-01,
       -1.39581161e-02, -6.86548837e-03,  9.37581901e-03,  1.33439288e-01,
       -1.84832513e-01, -4.52290982e-01, -8.67854655e-02, -6.52199835e-02,
       -1.49327554e-02, -1.06819466e-01,  5.96349835e-02,  7.58361518e-02,
       -1.61440343e-01,  1.10053495e-01,  5.15643843e-02,  1.48755819e-01,
       -6.22865818e-02, -1.27184317e-01,  2.14178368e-01,  3.00652552e-02,
       -2.91483045e-01, -3.88885178e-02,  5.06785288e-02,  2.53851384e-01,
        2.39825979e-01,  6.46663643e-03,  3.27748805e-02, -3.47091779e-02,
        1.16459504e-01, -3.24619502e-01,  1.07456952e-01,  2.46714815e-01,
        2.43919715e-02, 

In [ ]:
# Attendence Marking
video=cv2.VideoCapture(0)
# CSV file setup
csv_filename = "attendance_sheet.csv"
with open(csv_filename, mode='a', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Time"])
while True:
    success,frame=video.read()
    frames=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    face_loc=fr.face_locations(frames)
    # print(face_loc)
    face_enc=fr.face_encodings(frame,face_loc)
    # print(face_enc)
    for faceenc,faceloc in zip(face_enc,face_loc):
        match_check=fr.compare_faces(encoded_student_faces,faceenc)
        print(match_check)
        dist_check=fr.face_distance(encoded_student_faces,faceenc)
        print(dist_check)
        match_index=np.argmin(dist_check)
        
        if match_check[match_index]:
            name=std_name[match_index]
            print(name)
            # Write to CSV file
            with open(csv_filename, mode='a', newline='') as file:
                writer = csv.writer(file)
                writer.writerow([name, datetime.now().strftime("%Y-%m-%d %H:%M:%S")])
                
        else:
            name="unkown"
            print(name)
        y1,x2,y2,x1=faceloc
        cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,0),3)
        cv2.putText(frame,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),3)
        
    cv2.imshow("Face",frame)
    if cv2.waitKey(1)& 0XFF==ord('q'): 
        break
video.release()
cv2.destroyAllWindows()
    

[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1


[False, False, False, False, False]
[0.79248959 0.86950124 0.83744183 0.72258489 0.90306065]
unkown
[False, False, False, False, False]
[0.80155906 0.87719002 0.85570715 0.73304031 0.91207948]
unkown
[False, False, False, False, False]
[0.80499617 0.88620238 0.85179801 0.72047191 0.91629413]
unkown
[False, False, False, False, False]
[0.81094296 0.87654408 0.85932353 0.72386454 0.90931027]
unkown
[False, False, False, False, False]
[0.80322935 0.88044938 0.85043881 0.72260024 0.90812585]
unkown
[False, False, False, False, False]
[0.80979783 0.90703419 0.86774374 0.74701963 0.9384227 ]
unkown
[False, False, False, False, False]
[0.79759597 0.88354889 0.84376633 0.72690872 0.93617864]
unkown
[False, False, False, False, False]
[0.78905615 0.87685586 0.83145405 0.72533006 0.92808759]
unkown
[False, False, False, False, False]
[0.7696431  0.85866506 0.81051213 0.7087554  0.91316924]
unkown
[False, False, False, False, False]
[0.77048469 0.86854335 0.82655366 0.71324478 0.91525582]
unkown
