In [78]:
import cmake
import dlib
import numpy as np
import cv2
import face_recognition as fr
import os

In [79]:
path='images1'
# images folder path in 'path'
my_list=os.listdir(path)
print(my_list)
print(path)

['Amitabh Bachan.jpeg', 'Sachin.jpeg', 'Mother Teresa.jpeg', 'APJ Abdul Kalam.jpeg', 'Michel Jackson.jpeg']
images1


In [80]:
imgs=[]
class_name=[]

for img in my_list:
    path_img=os.path.join(path,img)
    # print(path_img)
    current_img=cv2.imread(path_img)
    # print(current_img)
    imgs.append(current_img)
    class_name.append(img.split('.')[0])
    
print(class_name)



['Amitabh Bachan', 'Sachin', 'Mother Teresa', 'APJ Abdul Kalam', 'Michel Jackson']
[array([[[130, 139, 119],
        [130, 139, 119],
        [129, 138, 118],
        ...,
        [135, 146, 126],
        [135, 146, 126],
        [135, 146, 126]],

       [[130, 139, 119],
        [130, 139, 119],
        [129, 138, 118],
        ...,
        [135, 146, 126],
        [135, 146, 126],
        [135, 146, 126]],

       [[130, 139, 119],
        [130, 139, 119],
        [129, 138, 118],
        ...,
        [135, 146, 126],
        [135, 146, 126],
        [135, 146, 126]],

       ...,

       [[178, 162, 120],
        [156, 140,  98],
        [185, 169, 127],
        ...,
        [133, 115,  78],
        [108,  90,  53],
        [115,  97,  60]],

       [[171, 155, 113],
        [159, 143, 101],
        [176, 160, 118],
        ...,
        [ 93,  75,  38],
        [ 95,  77,  40],
        [ 79,  61,  24]],

       [[176, 160, 118],
        [198, 182, 140],
        [158, 142, 100],
   

Why is face_location needed?

    Preprocessing for Recognition – Before recognizing a face, the model needs to detect and extract the face region.
    Improves Accuracy – Helps focus only on the face, ignoring background noise.
    Speeds Up Recognition – Instead of processing the whole image, it narrows down the area for recognition.

    # Print results
print(face_locations)  # Returns list of (top, right, bottom, left) coordinates
y1,x2,y2,x1=faceloc

If face_locations = [(50, 150, 200, 30)], it means:

    The face starts at y = 50 (top).
    Ends at y = 200 (bottom).
    Starts at x = 30 (left).
    Ends at x = 150 (right).

This helps in cropping or highlighting the detected face.

In [81]:
# Face Location and Encoding

# img=imgs[0]
# # print(img)
# img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
# face_in_frame=fr.face_locations(img)
# print(face_in_frame)



# pip list-all packages version
# numpy version-1.24.2-basic version supports Face recognition
# pip uninstall numpy
# pip install numpy==1.26.4 or 1.24.2 and restart

In [82]:
# face location encoding to collect accurate image

# encode=fr.face_encodings(img,face_in_frame)
# print(encode)

In [83]:
# #extract only required values
# encode=fr.face_encodings(img,face_in_frame)[0]
# print(encode)

In [84]:
def faceencoding(imgs):
    encodinglist=[]
    for img in imgs:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        face_in_frame=fr.face_locations(img)
        encode=fr.face_encodings(img,face_in_frame)[0]
        encodinglist.append(encode)
    return encodinglist



In [85]:
encodelist_knownfaces=faceencoding(imgs)
print(encodelist_knownfaces)

[array([-8.75804424e-02,  1.03788793e-01,  8.19521993e-02,  4.79343347e-04,
       -1.19748563e-01,  5.21378480e-02, -5.80289811e-02, -2.80814581e-02,
        9.58357304e-02, -3.14823277e-02,  1.27818123e-01, -2.11055167e-02,
       -1.96996614e-01,  7.14209378e-02,  1.00775007e-02,  5.00044301e-02,
       -1.36448190e-01,  5.79765812e-03, -1.32335559e-01, -9.35737491e-02,
       -2.23877504e-02,  9.85835642e-02,  3.04874871e-03, -2.56247576e-02,
       -1.27614379e-01, -3.45140398e-01, -9.13947225e-02, -6.05884865e-02,
        6.67693466e-02, -6.59556836e-02,  3.73633802e-02, -6.08676579e-03,
       -1.12851501e-01,  6.41506165e-03,  6.55505955e-02,  8.91589001e-02,
       -6.44013658e-02, -4.19219099e-02,  1.04495645e-01, -4.61151898e-02,
       -1.59736425e-01,  5.90023249e-02,  9.25934315e-02,  1.59770623e-01,
        1.46713465e-01,  1.50725365e-01, -3.23056877e-02, -7.62792081e-02,
        1.24618530e-01, -2.06127256e-01,  1.39338046e-01,  1.58372119e-01,
        5.41867921e-03, 

In [94]:
video=cv2.VideoCapture(0)
while True:
    sucess,frame=video.read()
    frames=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    face_in_frame=fr.face_locations(frames)
    # print(face_in_frame)
    encoded_face=fr.face_encodings(frame,face_in_frame)
    # print(encoded_face)
    
    for enc_face,faceloc in zip(encoded_face,face_in_frame):
        matches=fr.compare_faces(encodelist_knownfaces,enc_face)
        print(matches)
        
        face_dist=fr.face_distance(encodelist_knownfaces,enc_face)
        print(face_dist)
        
        matchindex=np.argmin(face_dist)
        print(matchindex)
        
        if matches[matchindex]:
            name=class_name[matchindex]
            print(name)
        else:
            name="unknown"
            print(name)
        y1,x2,y2,x1=faceloc
        cv2.rectangle(frame,(x1,y1),(x2,y2),(255,0,0),3)
        cv2.putText(frame,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),3)
            
        
            
    cv2.imshow("Face",frame)
    if cv2.waitKey(1)& 0XFF==ord('q'): 
        break
    
video.release()
cv2.destroyAllWindows()
# empty face=empty array
# single face=single_array
# two face=two array
# encoded_faces==[0] can be neglected since all faces need to be detected
# performance increase== face distance calculation
# compare training image with captured image==similar image==distance minimum

    
    

[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1


[False, False, False, False, False]
[0.71291276 0.6975465  0.79472656 0.73160992 0.75884045]
1
unknown
[False, False, False, False, False]
[0.67843606 0.69477415 0.7931997  0.74156786 0.77004567]
0
unknown
[False, False, False, False, False]
[0.67560243 0.7092064  0.7979017  0.74767032 0.77527206]
0
unknown
[False, False, False, False, False]
[0.78237947 0.73723544 0.73818463 0.76083489 0.74329906]
1
unknown
[False, False, False, False, False]
[0.63137265 0.66673224 0.70732813 0.74389661 0.73706445]
0
unknown
[False, False, False, False, False]
[0.62462094 0.65832418 0.68231801 0.69000973 0.71278617]
0
unknown
[False, False, False, False, False]
[0.67814907 0.72408056 0.69795536 0.71580328 0.71864134]
0
unknown
[False, False, False, False, False]
[0.70026092 0.7391345  0.72939354 0.73733963 0.74166717]
0
unknown
[False, False, False, False, False]
[0.67748426 0.71168468 0.72307692 0.72720866 0.72169864]
0
unknown
[False, False, False, False, False]
[0.67581997 0.7205748  0.73610707 0.7