In [ ]:
file=open("/content/IndiaUS.txt",'r',encoding='utf-8')
mytext=file.read()
print(mytext)


Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country's partnership with India among the "most consequential in the world". The BBC's Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit's potential in strengthening the ties between the two nations.

The US's relationship with India - the world's most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.

The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.

A key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China's growing influence in the Indo-Pacific. India-US t

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense
import pickle

In [ ]:
mytokenizer=Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words=len(mytokenizer.word_index)+1
# Actually len is 598,but +1 is added bcos since we are padding 0 since every sentence may not have equal words
total_words


599

In [ ]:
mytokenizer.word_index
# this is json format.

{'the': 1,
 'to': 2,
 'in': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'has': 12,
 'that': 13,
 'biden': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'but': 20,
 'on': 21,
 'washington': 22,
 'an': 23,
 'it': 24,
 'says': 25,
 'will': 26,
 'are': 27,
 'indian': 28,
 'prime': 29,
 'minister': 30,
 'this': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'relationship': 37,
 'been': 38,
 'about': 39,
 'strategic': 40,
 'more': 41,
 'up': 42,
 'during': 43,
 'also': 44,
 'make': 45,
 'sirohi': 46,
 'china': 47,
 'air': 48,
 'force': 49,
 'state': 50,
 'his': 51,
 'ties': 52,
 'two': 53,
 'at': 54,
 'white': 55,
 'house': 56,
 'be': 57,
 'lot': 58,
 'ms': 59,
 'technology': 60,
 'jet': 61,
 'semiconductor': 62,
 'now': 63,
 'first': 64,
 'was': 65,
 'global': 66,
 'one': 67,
 'he': 68,
 'without': 69,
 'they': 70,
 'narendra': 71,
 'joe': 72,
 'world': 73,
 'potential': 74,
 'how': 75,
 'becom

In [ ]:
with open('tokenizer.pickle','wb') as handle:
  pickle.dump(mytokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)
  # wb=write binary
  # By pickling the Tokenizer, you are essentially saving its state
  # to a file. This allows you to load it later and reuse it without
  # having to re-train it on the same text data.
  # This is particularly useful when you have a large dataset
  # and want to avoid repeating the tokenization process every time.

In [ ]:
my_input_sequences=[]
for line in mytext.split('\n'):
  token_list=mytokenizer.texts_to_sequences([line])[0]
  # print(token_list)
# token_list is in numerical format to work in model
  for i in range(1,len(token_list)):
    n_gram_sequence=token_list[:i+1]
    # bigram,i+2 trigram
    my_input_sequences.append(n_gram_sequence)

In [ ]:
max_sequence_len=max([len(x) for x in my_input_sequences])
max_sequence_len

83

In [ ]:
min_sequence_len=min([len(x) for x in my_input_sequences])
min_sequence_len

2

In [ ]:
'''
[1,2,3,5]==>[1,2,3,5,0]
[2,5,6]=>[2,5,6,0,0]
[2,5,6,2,4]==>[2,5,6,2,4]
'''

'\n[1,2,3,5]==>[1,2,3,5,0]\n[2,5,6]=>[2,5,6,0,0]\n[2,5,6,2,4]==>[2,5,6,2,4]\n'

In [ ]:
input_sequences=np.array(pad_sequences(my_input_sequences,maxlen=max_sequence_len,padding='pre'))

In [ ]:
input_sequences
input_sequences[400]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,  26,
       290,  16,   4, 291, 120,   7,   1, 292, 293, 294, 295, 296, 129,
        82, 122, 297,  83,  26,  44, 298,  42,   4, 130,   3,   6,   1,
       129,  26,  57, 299,   3,   6,  83, 300, 131,   8,  80, 301,   3,
       302, 303,   1,   9, 304, 124, 305,   7,  18, 126,  84,  10,   1,
       132, 306, 307,  20, 308], dtype=int32)

In [ ]:
x=input_sequences[:,:-1]
y=input_sequences[:,-1]

In [ ]:
x[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 99,  4],
      dtype=int32)

In [ ]:
y[1]

177

In [ ]:
# one hot encoding
y=np.array(tf.keras.utils.to_categorical(y,num_classes=total_words))

In [ ]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words,activation='softmax'))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=100,verbose=1)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 9s 134ms/step - accuracy: 0.0397 - loss: 6.2752
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 10s 135ms/step - accuracy: 0.0598 - loss: 5.7751
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 11s 147ms/step - accuracy: 0.0510 - loss: 5.6830
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 11s 174ms/step - accuracy: 0.0541 - loss: 5.6927
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 10s 182ms/step - accuracy: 0.0555 - loss: 5.5581
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 8s 134ms/step - accuracy: 0.0576 - loss: 5.4833
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - accuracy: 0.0519 - loss: 5.4341
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 9s 155ms/step - accuracy: 0.0735 - loss: 5.1807
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 9s 136ms/step - accuracy: 0.0913 - loss: 5.0410
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 10s 134ms/step - accuracy: 0.1188 - loss: 4.7882
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 11s 147ms/step - accuracy: 0.1483 - loss: 4.5175
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━

In [ ]:
model.save("word_prediction_model.h5")

In [ ]:
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 82, 100)             │          59,900 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 150)                 │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 599)                 │          90,449 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 902,849 (3.44 MB)

 Trainable params: 300,949 (1.15 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 601,900 (2.30 MB)

None


In [ ]:
# Prediction
import numpy
import pickle
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import pickle

In [ ]:
with open('/content/tokenizer.pickle','rb') as handle:
  mytokenizer=pickle.load(handle)

model=tf.keras.models.load_model('/content/word_prediction_model.h5')

In [ ]:
input_text="india"

predict_next_words=10


for i in range(predict_next_words):
  token_list=mytokenizer.texts_to_sequences([input_text])[0]
  token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
  predicted=np.argmax(model.predict(token_list),axis=-1)
  # print(predicted)
  output_word=mytokenizer.index_word[predicted[0]] #converted index to word
  input_text+=" "+output_word
print(input_text)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
india will proceed with a 3bn purchase of the battle tested


In [ ]:
# when we need to predict more words ,after certain word it may predict  same words or meaningless sentences.hence we introduced LLM